image: node:argon

cache:
  paths:
    - node_modules/

variables:
  GIT_DEPTH: "10"
  GIT_STRATEGY: fetch

before_script:
  - env
  - git --version
  - npm --version
  - node --version

test:
  script:
    - npm install
    - npm test -- --silent || npm test
